package mastodon

import "github.com/arrow2nd/nekomata/api"

const (
	endpointOauthAuthorize   api.Endpoint = "/oauth/authorize"
	endpointOauthToken       api.Endpoint = "/oauth/token"
	endpointAnnouncements    api.Endpoint = "/api/v1/announcements"
	endpointStatuses         api.Endpoint = "/api/v1/statuses"
	endpointFavourite        api.Endpoint = "/api/v1/statuses/:id/favourite"
	endpointUnfavourite      api.Endpoint = "/api/v1/statuses/:id/unfavourite"
	endpointReblog           api.Endpoint = "/api/v1/statuses/:id/reblog"
	endpointUnreblog         api.Endpoint = "/api/v1/statuses/:id/unreblog"
	endpointBookmark         api.Endpoint = "/api/v1/statuses/:id/bookmark"
	endpointUnbookmark       api.Endpoint = "/api/v1/statuses/:id/unbookmark"
	endpointAccounts         api.Endpoint = "/api/v1/accounts/:id"
	endpointRelationships    api.Endpoint = "/api/v1/accounts/relationships"
	endpointAccountsSearch   api.Endpoint = "/api/v1/accounts/search"
	endpointAccountsStatuses api.Endpoint = "/api/v1/accounts/:id/statuses"
	endpointFollow           api.Endpoint = "/api/v1/accounts/:id/follow"
	endpointUnfollow         api.Endpoint = "/api/v1/accounts/:id/unfollow"
	endpointBlock            api.Endpoint = "/api/v1/accounts/:id/block"
	endpointUnblock          api.Endpoint = "/api/v1/accounts/:id/unblock"
	endpointMute             api.Endpoint = "/api/v1/accounts/:id/mute"
	endpointUnmute           api.Endpoint = "/api/v1/accounts/:id/unmute"
	endpointTimelinePublic   api.Endpoint = "/api/v1/timelines/public"
	endpointTimelineHome     api.Endpoint = "/api/v1/timelines/home"
	endpointTimelineList     api.Endpoint = "/api/v1/timelines/list/:list_id"
	endpointStreaming        api.Endpoint = "/api/v1/streaming"
	endpointMedia            api.Endpoint = "/api/v1/media/:id"
	endpointMediaUploadAsync api.Endpoint = "/api/v2/media"
)
